version: "3"

services:
  gemini-web-vuln-detection:
    image: noobpk/gemini-web-vuln-detection
    environment:
      - AUTH_KEY="your-authen-key"
      - ENABLE_KAFKA_STREAMING=False
      - KAFKA_BOOTSTRAP_SERVER=
      - KAFKA_TOPIC=gemini-data-streaming
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
    ports:
      - "5000:443"
    container_name: gemini-web-vuln-detection
    restart: unless-stopped