version: "3"

services:
  gemini-web-vuln-detection:
    image: gemini-web-vuln-detection
    build: .
    environment:
      - AUTH_KEY=your-authen-key
    ports:
      - "5000:443"
    container_name: gemini-web-vuln-detection
    restart: unless-stopped
