version: "3"

services:
  gemini-web-vuln-detection:
    image: gemini-web-vuln-detection
    build: .
    environment:
      - AUTH_KEY=
      - ENABLE_KAFKA_STREAMING=
      - KAFKA_BOOTSTRAP_SERVER=
      - KAFKA_TOPIC=gemini-data-streaming
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
    ports:
      - "5000:443"
    container_name: gemini-web-vuln-detection
    restart: unless-stopped
